@baseUrl = http://localhost:3001/api/user
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NzEzYjI0MS0yNTc0LTQxZTQtOGM4Yi03ZWEwN2Q2NGVjZWUiLCJlbWFpbCI6Im5kdHJpMjNAY2xjLmZpdHVzLmVkdS52biIsImlhdCI6MTc4NTE1NzE3OSwiZXhwIjoxNzg1MTU4MDc5fQ.gXN4Ekg57HBZUsoYmS5lK47bmJtmPkAc-4HgEPvPqAQ
@userId = 6713b241-2574-41e4-8c8b-7ea07d64ecee

### Get personal information (Get Me)
GET {{baseUrl}}/me
Cookie: accessToken={{token}}

### Get User information by ID
GET {{baseUrl}}/{{userId}}
Cookie: accessToken={{token}}

### Update Profile
# Note: Currently your route is PATCH / but the UpdateProfileSchema schema requires params.id
# and the controller is getting req.params.id, so this api will fail.
# Hint: If "Update Me", you should get `req.user.userID` instead of `req.params.id`.
# If updating by ID, the route must be PATCH /:id
PATCH {{baseUrl}}/
Cookie: accessToken={{token}}
Content-Type: application/json

{
    "phone": "123123213",
    "avatar_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuDGi1_AVK3XUdN5cS9tUBuYhgg9UhK3zN0hA_3b6M-Q&s=10"
}
